### ISSUE TITLE
nits: setup: Font color not right when setup is done

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#142]
See attached pic:

<img width="184" alt="image" src="https://github.com/spr-networks/super/assets/1476421/21f1cc60-c7e5-4367-b024-4755d3698904">
<img width="177" alt="image" src="https://github.com/spr-networks/super/assets/1476421/7fba575e-ab93-487b-9e54-cc365247049d">

**Comment by lts-po** [comment]
Fixed in dev ( https://github.com/spr-networks/super/commit/d00735d97dc77383ba8da2bbf5b8738e10ca4b26 )
