### ISSUE TITLE
nits: ui: DNS Log: Select client input box

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#143]
The input box on that UI has an annoying behavior; you can't click on it to display the various clients but have to click on the arrow on the far right of the box

https://github.com/spr-networks/super/assets/1476421/80c98e70-e5e8-4384-8bad-1c53392da9d2

**Comment by lts-rad** [comment]
Good question about why this happens, any ideas @lts-po?

I think the Native Base 'Menu' is the relevant code?

https://github.com/spr-networks/super/blob/efd50684d7fd5aeebd1f34b9361860612fe63feb/frontend/src/components/InputSelect.js
