### ISSUE TITLE
dng log: Delete history doesn't seem to do anything

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#148]
I have a device that I added to the DNS ignore list later on, so wanted to clear the DNS history for it as well. Clicking on the delete button doesn't seem to do anything; no obvious exception either (running 0.2.7):

https://github.com/spr-networks/super/assets/1476421/17f4e803-6d13-4556-98e9-92d78ecf1190

**Comment by lts-po** [comment]
Fixed in latest release, thanks!

**Comment by 0vercl0k** [comment]
Awesome, just verified it works!

Cheers
