### ISSUE TITLE
ui/ios: list of connected devices

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#162]
On iOS, there's no good way (AFAIK) to display the list of connected devices; the connected devices are highlighted like they are in the Web UI.

**Comment by lts-po** [comment]
Currently you can view connected devices under Wifi -> Clients tab.

There will be a rewrite of the device listing to include wifi info when connected (a bit redundant with both views). Will make sure to include connected status.

Thanks!

**Comment by 0vercl0k** [comment]
Oh I missed that, this is perfect for me, thank you! Feel free to close
this.

Cheers
