### ISSUE TITLE
ios/add domain override: trailing dot in the DNS name

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#166]
I added a domain override using the 'Add Domain Override' menu but the DNS name included a trailing `.`; like `foo.com.`.

**Comment by lts-rad** [comment]
Can clean up the UI here. It should work okay, I need to recall the reasoning for the trailing .

**Comment by 0vercl0k** [comment]
Oh interesting, I guess I didn't try to validate 😅 Also, the entry appears w/ the IP of the client once it has been added; it'd be nice if it could also show the associated name.
