### ISSUE TITLE
superdns in error loop

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#176]
My superdns container logs have tens or hundreds of MBs of entries:

```
[ERROR] Recovered from panic in server: "dns://:53" runtime error: invalid memory address or nil pointer dereference
```

The router (Clearfog) has a working Internet connection and DNS. Clients can route traffic to the Internet but cannot resolve DNS via the router.

```
; <<>> DiG 9.10.6 <<>> @10.0.0.1 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 710
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; Query time: 18 msec
;; SERVER: 10.0.0.1#53(10.0.0.1)
;; WHEN: Mon Jul 10 20:27:49 PDT 2023
;; MSG SIZE  rcvd: 39
```

Restarting the container, the full docker compose stack, or the entire router did not resolve the issue.

**Comment by rgov** [comment]
After rebooting my device clock was wrong. After syncing the clock DNS started working for clients.

I do not know if this was the initial problem.

**Comment by lts-rad** [comment]
@rgov i think so as the  configuraiton uses dns over https which is time sensitive for certificate dates. i think we need to ensure the clearfog buildroot is running ntpdate to stay online.

**Comment by lts-rad** [comment]
the panic is fixed now at least and theres stacktraces with errors from dns if there is a panic now in the default config.
