### ISSUE TITLE
Pi image has password SSH auth disabled

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#177]
I flashed release 0.2.16 to a USB drive and booted a Raspberry Pi off of it, following [the instructions](https://www.supernetworks.org/pages/docs/pi4b). 

The file `/etc/ssh/sshd_config.d/60-cloudimg-settings.conf` contained the `PasswordAuthentication no` setting so I wasn't able to SSH into the system to do any administration. The instructions seem to indicate it should work.

This is also inconsistent with the Clearfog release.

**Comment by rgov** [comment]
Thought it should work? Did my install script not finish?

https://github.com/spr-networks/super/blob/4bbdc3c75892d042d3bddde1304356370ba62400/installer/scripts/install.sh#L50

**Comment by rgov** [comment]
I reproduced the issue. The install script needs to be updated.

**Comment by lts-rad** [comment]
❤️ thanks @rgov. this looks like a regression with karmic
