### ISSUE TITLE
Pi is only showing wlan0 interface

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#179]
The setup guide implies that the USB Wi-Fi dongle will be wlan1 while the built-in interface wlan0 cannot be used:

> The current setup assumes you'll be using a Raspberry Pi Model 4b with an mt76 based wireless adapter (wlan1).

> Note that the built-in Raspberry PI Wireless card can not be used as an AP by default as it does not support AP/VLAN, which is a feature that SPR relies on.

However only wlan0 appears in the UI and therefore I had to proceed with setup with that interface.

**Comment by rgov** [comment]
I rebooted (and reseated the USB stick, which seemed to be pretty secure already) and got wlan1.

**Comment by lts-rad** [comment]
looks like this is new in karmic. will look at assigning since it seems newer kernels might enumerate usb first
