### ISSUE TITLE
Auth migration fails if destination folder doesn't exist

### ISSUE THREAD

**Issue by wwong** [spr-networks/super#193]
When upgrading from an older version, the `/configs/auth` doesn't exist, which causes `os.Create` to error out when attempting to create a new file. Manually running `mkdir ./configs/auth` seems to have fixed things.

See: https://github.com/spr-networks/super/blob/901d0dee089cd8359e0a40654432690ee4f7d247/api/code/auth.go#L40

**Comment by lts-rad** [comment]
Thanks! Would you remember if this was an update from the UI and your previous version?

If the git repo is up to date, docker compose-up is responsible for making the  folder

**Comment by wwong** [comment]
I think it was a UI update from a fresh 0.2.7 image to 0.2.22. I had to manually `git pull` to get the repo updated.

**Comment by lts-rad** [comment]
there was previous a bug where superd would not update the git repo for the spr directory, so i think that fix would address this bug

**Comment by lts-rad** [comment]
https://github.com/spr-networks/super/commit/a21fda3d09c92c6d258b2b66191b78751026cdcd

**Comment by lts-rad** [comment]
sorry you got bit by this @wwong
