### ISSUE TITLE
Log stacktraces on error

### ISSUE THREAD

**Issue by wwong** [spr-networks/super#195]
I sometimes see random errors in the log output with no real way to follow up on them.

Consider the following log line - it would be nice to know which JSON file was being parsed:
```
IMAGE_NAME=ghcr.io%2Fspr-networks%2Fsuper_api%3Alatest unexpected end of JSON input
```

**Comment by lts-rad** [comment]
is this logs under docker-compose logs? 

we have a little bit more information under http://spr/admin/events where there's at least a link to the line that prints the error

**Comment by lts-po** [comment]
This is enabled in v0.2.23+
