### ISSUE TITLE
Add DNS Block Bug - DNS Log page doesn't apply other inputs

### ISSUE THREAD

**Issue by cwhitlock-it** [spr-networks/super#244]
On the "DNS Log" page. If you select the icon to create a block for that request. The client IP is auto populated, if you edit the "Client IP" field to nothing or "*" and add that block the client IP is still populated and the block is not applied to other devices.

This is not the case if you manually add a block on the "DNS Overrides" page, it defaults to * and applies to all device or can be set per client.

<img width="243" alt="image" src="https://github.com/spr-networks/super/assets/149862607/f72c703e-adad-467d-a0a1-e77473869fc1">
<img width="476" alt="image" src="https://github.com/spr-networks/super/assets/149862607/8e93074c-7540-412f-a00e-a37815acba29">

**Comment by lts-rad** [comment]
Thanks again for this, fix will be in the next release
https://github.com/spr-networks/super/commit/38288ffa6e882ffb18ade2f4d7c8ad562a21816e
