### ISSUE TITLE
UI should warn when DNS container fails to start

### ISSUE THREAD

**Issue by wwong** [spr-networks/super#256]
Super-DNS hit a port bind conflict with systemd-resolve, resulting it the DNS container not starting:
```
superdns               | Listen: listen tcp :53: bind: address already in use
```

**Comment by lts-rad** [comment]
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/94c1e3c0-353d-463e-9d07-9af7fd2282e4">
this is going out in the next release
