### ISSUE TITLE
ui: ios: glitch when enabling/disabling DNS Block list

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#259]
Check the top left corner where you see a window appearing and disappearing real quick.

https://github.com/spr-networks/super/assets/1476421/4a664955-44da-46f6-a6b4-e19d446f0415

**Comment by lts-po** [comment]
This should be fixed in latest gluestack (+ close menu on select).
Will push 0.3.5 soon with updated version & minor fixes
