### ISSUE TITLE
ui: ios: 'Add templates' button in 'Alert configuration'

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#260]
The button doesn't too small / truncated
<img width="299" alt="addalertstemplates" src="https://github.com/spr-networks/super/assets/1476421/328033e9-f7b7-4b09-b9fa-35dcf6f80f7d">

**Comment by lts-po** [comment]
Thanks! This is fixed in dev, will be in next release.
https://github.com/spr-networks/super/commit/e27d9f2dbb3e8a883097c4496161b837c262f944
