### ISSUE TITLE
Outbound traffic view empty

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#262]
I've been running into this for the past few days; basically the 'outbound traffic' view is empty (both on iOS & website). I've looked at some of the log and this one might be relevant (from `superdb`):
```
2024/01/15 16:40:12 [-] Empty db configuration, initializing
```

<img width="563" alt="image" src="https://github.com/spr-networks/super/assets/1476421/728e7e49-9075-4bec-98e6-096f64daf6a1">

**Comment by lts-rad** [comment]
to diagnose:

1. traffic can be retreived with these calls:

curl -u admin:admin http://spr.local/traffic_history
curl -u admin:admin http://spr.local/iphistory

do these return 200? data?

2. if the above failed do you see `table ip accounting ` if you run "nft list ruleset | less" ?

**Comment by lts-rad** [comment]
As for the log configuration log that is expected until a user has customized their events. that error is probably too verbose then. it will use the defaults

```
        // default config
        config := &LogConfig{
                SaveEvents: []string{"log:api", "dns:block:event", "dns:override:event", "dns:serve:", "wifi:auth:", "auth:failure:"},
                MaxSize:    250 * 1024 * 1024, //bytes
        }
        data, err := ioutil.ReadFile(gConfigPath)
``

**Comment by 0vercl0k** [comment]
Okay so hitting `iphistory` returns a 404, `traffic_history` does return something that looks healthy. I also see a `table ip accounting` ruleset.

**Comment by lts-rad** [comment]
so the right function was `iptraffic` not `iphistory`. 

`curl -u admin:admin http://192.168.2.1/iptraffic`


on the router you can check:

nft -j list set ip accounting all_ip;


I suspect this is empty for some reason.

**Comment by 0vercl0k** [comment]
Hitting `iptraffic` seems to return some healthy data, and `nft -j list set
ip accounting all_ip;` as well (it is not empty either) 🤔

**Comment by lts-rad** [comment]
okay so tracked this down

```func updateFirewallSubnets(DNSIP string, TinyNets []string) {
	//update firewall table rules to service the new tiny networks, where needed
	flushSupernetworkEntries()
	for _, supernet := range TinyNets {
		addSupernetworkEntry(supernet)
	}
```

seems like local_lan is missing the full supernets entries. lets see why this isnt running ons tartup

**Comment by lts-rad** [comment]
startup goes initDHCP-> loadDHCPConfig -> 
	updateFirewallSubnets(getLANIP(), gDhcpConfig.TinyNets)

its unclear then how this would get out of sync

**Comment by lts-rad** [comment]
closing for now

**Comment by 0vercl0k** [comment]
Thanks again for figuring it out!
