### ISSUE TITLE
Unused groups don't get garbage collected

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#264]
If I create a group 'foo' for a set of devices, and then remove those devices off the group; 'foo' is still visible in the 'Groups' view and I can't find a way to get it removed (on website / iOS).

**Comment by lts-rad** [comment]
dc514dfaef3e8af2f12a1e84841c4c168ec7a4cc adds UI functionality to delete an empty group

**Comment by 0vercl0k** [comment]
Cool thank you, just verified it works!
