### ISSUE TITLE
Wireguard Default Endpoint Ignored During Add Peer

### ISSUE THREAD

**Issue by d-a-v-e-g** [spr-networks/super#266]
The Default Endpoint when set will not be reflected as the default when you add a peer.  Repro: Set the default endpoint, add a peer without specifying the endpoint, observe the Endpoint value in the Peer settings.

**Comment by lts-rad** [comment]
this has been addressed by @94e69bb5860a59dcc2b28080d5319d139962aeb3 

 @lts-po:

a combo of things caused this here. first this uses the older react style component which uses this.setState, which has more state transitions. second this about state in select, which react always gets wrong.
