### ISSUE TITLE
ui: ios: SystemInfo view, Service Container Logs edit box masked by events

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#267]
![image](https://github.com/spr-networks/super/assets/1476421/bb3c328e-8717-4cb8-afd1-fddb27c22b3b)

**Comment by lts-po** [comment]
Thanks! Fixed in dev & will be avail in next release.

**Comment by 0vercl0k** [comment]
This also looks like it can be closed - verified it's fixed in latest!
