### ISSUE TITLE
ui: website: Bandwidth Timeseries doesn't pull device names

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#268]
I've noticed that the 'Bandwidth timeseries' UI only pulls the device's name if you click on the 'Data' button but not otherwise.

**Comment by lts-po** [comment]
Thanks! Fixed in dev & will be avail in next release.

**Comment by 0vercl0k** [comment]
Cool this works! I did noticed something that might not be expected - FYI I do see one device whose IP can't be pulled and it matches the IP of the router itself (the IP where the web administration is at).
