### ISSUE TITLE
ui: ios: Adding a device, pressing return submit the form / cannot scroll to expiry

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#269]
There's a behavior that is a little bit annoying when adding a new device. Assigning the name pull the keyboard which hides and make it hard to configure other options, especially the ones that are at the bottom of the page as somehow you can't access them by scrolling down:

https://github.com/spr-networks/super/assets/1476421/ff8ead59-c914-47ab-b31e-4582af00de3b

If you press return on the keyboard it validates the form which generates the QR code and skip to the next UI. So I need to select into another edit box, and press return (in other edit box, pressing return just remove the keyboard without validating it) to then be able to scroll all the way down.

It's unclear if this behavior is meant to be able to add a device really fast by just assigning a name as it's probably what users do the most or if it's a bug, lemme know!

**Comment by lts-po** [comment]
Got a fix for this now! :) Should be for add device view & also if other forms have the same issue.
Will push new app soon, Thanks again for your reports @0vercl0k

**Comment by 0vercl0k** [comment]
No worries at all @lts-po, thank you for all the fixes :) I believe this is fixed in the latest fwiw
