### ISSUE TITLE
ui: ios: Removing a device is super glitchy

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#271]
If you have a few devices (like 5-10), removing one of them with left swipe end up kinda triggering a weird UI effect where it sort of glitches. Sometimes it feels like there's buttons getting rendered behind each 'device' like in the below:

<img width="273" alt="image" src="https://github.com/spr-networks/super/assets/1476421/3e44c645-3aeb-4f72-9692-51c56f9875ca">

**Comment by lts-po** [comment]
Fixed & new version will be avail on App Store soon, thanks!
