### ISSUE TITLE
An already created device doesn't seem to be able to be turned into an expiring one

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#272]
If a device is created and then later you try to give it an expiry the UI it doesn't seem to work; the parameter doesn't get saved. Not sure if this is expected, but if this is the case maybe greying those controls out would be better for users to realize that

**Comment by lts-po** [comment]
Fixed in dev now, ty
Added support for 1h-1month / Never for already added devices. Skipping custom timestamp.
