### ISSUE TITLE
feature request: Option to display the connection QR code if the user needs it

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#275]
There's been a few times that I'd have loved to have an option to show the connection QR code for an already existing device.

Sometimes this device has been migrated and doesn't have the password stored anymore, or sometimes an iOS device sync the passphrase of another one, etc. When you run into this case, it's easier to remove / add a new device but then you are loosing the configuration associated with it which is extra friction.

**Comment by lts-po** [comment]
v0.3.5 now have this feature under device listing  -> Show password

**Comment by 0vercl0k** [comment]
I've tried it out - it's awesome! Thank you!
