### ISSUE TITLE
ios: ip of the router defaults to 192.168.2.1

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#276]
It'd be nice if the iOS could cache the IP of where SPR is at or just defaults with the gateway defined on the network interface. My set-up doesn't use the `192.168.2.x` network and so every time the application is killed / phone rebooted, I need to update the IP when logging in via the app.

**Comment by lts-rad** [comment]
can do. one other thing here is to look into how the react deals with a self signed certificate, havent checked on this yet but i think its going to be a pain point

**Comment by lts-po** [comment]
Thanks! This is fixed now in dev, stores hostname if login successful. Will be in the next release.

**Comment by 0vercl0k** [comment]
This is also fixed as far as I can tell!
