### ISSUE TITLE
 device expiry time calculation seems broken in UI

### ISSUE THREAD

**Issue by lts-rad** [spr-networks/super#282]

**Comment by lts-rad** [comment]
@0vercl0k i have not been able to reproduce this yet

**Comment by lts-rad** [comment]
need to test closer to 0 GMT in case this is a bug with the timeAgo.js package

**Comment by lts-rad** [comment]
smells like https://github.com/hustcc/timeago.js/issues/222

**Comment by 0vercl0k** [comment]
i'm happy to try to repro again or help in any way :) Give me a shout!

**Comment by lts-rad** [comment]
Expire in ${timeAgo(
        new Date('07 Feb 2024 03:39:31 GMT').toUTCString()
      , 'en_US', {relativeDate: '07 Feb 2024 02:26:31 GMT'})}

correctly reports 1 hour at least

**Comment by lts-rad** [comment]
seems like the issue is not with the rendering. perhaps a UI state error with inputting the wrong time

**Comment by lts-po** [comment]
@0vercl0k think its related to editing a pending device, does it work ok when editing a device that is not pending / after its auth'd? pushing a fix that will handle this for pending devices

**Comment by 0vercl0k** [comment]
I've just tried it out - it seems the UI behaves the same way if I connect
a device "Expire in 8 minute ago". But the device actually doesn't seem to
be auto removed so maybe it's just a UI display issue?
