### ISSUE TITLE
ios: ui: Enabling / Disabling DNS Blocklists doesn't seem to update the counter

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#292]
If I go ahead and turn all the DNS block lists off, the aggregate number of blocked DNS doesn't seem to be updated

**Comment by lts-po** [comment]
Domains should be added within 5-10 sec, running in background so metrics don't update right away.
Should show correct from a page refresh after 5sec or so. Adding code that will fetch this & update when domains are added.
Thanks!

**Comment by lts-rad** [comment]
semi related -- v0.3.7 will have a fix that makes coredns start up faster
