### ISSUE TITLE
feature request: ios: ui: refreshing data when app is in foreground

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#293]
I'm not too sure what's the right way of doing this - but basically, every time I pull the app on the index page, I need to click on another tab and click again to go back to the main tab to have it refresh data.

I think ideally, having it auto refresh when the app is back on foreground would work well - but if that's not feasible, maybe a small refresh button somewhere could just do the work.

**Comment by lts-rad** [comment]
@lts-po thoughts on dashboard refresh? i wonder why its not happening on ios

**Comment by lts-rad** [comment]
i wonder if we can do a universal hook, 
https://www.strictmode.io/articles/react-pull-to-refresh
