### ISSUE TITLE
ui: ios: device tag color

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#296]
In the latest version, the device tag color changed to a color super bright that makes it hard to read
<img width="266" alt="repro" src="https://github.com/spr-networks/super/assets/1476421/af15c268-d4d0-4db8-a5e9-e758afc56ac6">

**Comment by lts-po** [comment]
Looks like it's the bg from light color theme - does it work flipping colormode bright/dark or is it stuck like this? (And only in the device view or others also)
Is this v0.3.5 of the iOS app or the TestFlight version?

Thanks

**Comment by 0vercl0k** [comment]
The color is stuck like this even after clicking the light mode button -
this is the case for all devices. I think it's only in the device view, I
don't think I've noticed it elsewhere. This was v0.3.6!

Cheers

**Comment by lts-po** [comment]
Thanks! Fixed now in version on TestFlight, will be a change from default groups (lan, wan, dns) to policies in next release, see: https://github.com/spr-networks/super/issues/290

**Comment by 0vercl0k** [comment]
Awesome - I am loving this simplification as I was always a bit confused 😅
Good job guys!

Cheers
