### ISSUE TITLE
ios: 'Traffic Last 5 minutes / hour' doesn't display the device names

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#308]
I noticed that for a build or two (0.3.7) the 'traffic last x' widget doesn't show the device name anymore. It shows the counters as well as the icon that was configured for the device but not the name; it's empty.

**Comment by 0vercl0k** [comment]
Adding screenshot for reference
![d](https://github.com/spr-networks/super/assets/1476421/a789ece4-1948-44c9-8e62-59df25d647ef)

**Comment by lts-po** [comment]
Thanks for the report! Cleaned up a little too much there, Fixed in TestFlight (up soon) & new release soon!

**Comment by 0vercl0k** [comment]
Awesome, thank you so much!
