### ISSUE TITLE
Some broken doc links

### ISSUE THREAD

**Issue by cocochpie** [spr-networks/super#314]
These are broken
- https://github.com/spr-networks/super/blob/main/README.md?plain=1#L114-L116
```
Documentation Home: https://www.supernetworks.org/pages/docs/intro/  (need to remove last slash character)
Raspberry Pi 4 Setup https://www.supernetworks.org/pages/docs/pi4b  (/setup_guides/ is missing)
General Setup Guide https://www.supernetworks.org/pages/docs/setup_run_spr  (/setup_guides/ is missing)
```

OUI vendor list is now 404 - https://www.supernetworks.org/pages/docs/services/plugin_lookup
- https://www.wireshark.org/download/automated/data/manuf

**Comment by lts-po** [comment]
Thanks! Fixed now in dev & will merge
