### ISSUE TITLE
LAN_UPSTREAM tag leftover

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#316]
I think I used in the past (probably wrongly) the `LAN_UPSTREAM` tag (or was it a group?) and it shows up as the below in latest versions:

<img width="296" alt="1" src="https://github.com/spr-networks/super/assets/1476421/7225ec5d-c84b-4eae-a67c-00f324d0f3fb">

I know you guys updated the languages / made tag/groups way less confusing (thank you again!) so I wonder if it was supposed to strip this `LAN_UPSTREAM` off.

I also don't seem to be able to delete it myself from the UI as far as I can tell.

Cheers

**Comment by lts-rad** [comment]
my expectation would be that these are automatically migrated for v > 0.3.7 . 

under configs/devices/devices.json do you have the Groups array for this device?

**Comment by 0vercl0k** [comment]
Actually, the group array for that device is empty; but I do see a `lan_upstream` in the `Policies` array

**Comment by lts-rad** [comment]
ok so then its just the ui thats not making the distinction well then, we should split out groups from policy better
