### ISSUE TITLE
Time is always off on my SPR router

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#317]
I think I have always noticed that somehow the time is always off on my SPR router, but I didn't really care too much. But since there's now the OTP, the time actually matters as otherwise I just keep getting wrong OTPs which prevents me from accessing feature like showing the WiFi password, etc.

Is this something you guys have noticed? How do I help debug that?

Cheers

**Comment by lts-rad** [comment]
i think this is a bug we need to fix on clearfog . i will make sure we are running date

ntpdate -s time.nist.gov

**Comment by lts-rad** [comment]
https://github.com/spr-networks/SuperTBD/issues/121

**Comment by Tiecoon** [comment]
https://github.com/spr-networks/cn913x_build/commit/ec8fb940a0253927579b74ed1269443256789c80
ntpdate.service in this commit fails to start on my box, using systemd-timesyncd instead seems to solve this on my box

**Comment by Tiecoon** [comment]
ntpdate seems to be located at /usr/sbin/ntpdate

**Comment by lts-rad** [comment]
Finally getting to this, thanks @Tiecoon . https://github.com/spr-networks/cn913x_build/commit/80d90f10fc932bef2719ea2be155dd229d40605c
