### ISSUE TITLE
Checkbox not reflecting actual "enabled" status of interface in link settings

### ISSUE THREAD

**Issue by avlidienbrunn** [spr-networks/super#330]
## Description
When editing interface settings in `/admin/uplink` (click triple dot -> Modify Interface), the checkbox displaying "enabled" status does not reflect the value of the setting. The checkbox is always checked, regardless of wether the interface is "enabled" or not.

The green `ENABLED` label works as intended:

![image](https://github.com/spr-networks/super/assets/1272648/79822c91-441b-40e2-a22a-4e61e6aa5dc6)

**Comment by lts-rad** [comment]
picking this up now. seeing the onClose not defined error as well

**Comment by lts-rad** [comment]
- [ ] fix scroll view for uplink
- [ ] fix onClose for lan link view
- [ ] fix ssid escaping 
- [ ] fix dhcp

**Comment by lts-rad** [comment]
3cca32da1a747e7a8a32f1434c099374136a3701

**Comment by lts-rad** [comment]
Next release should have this fix
