### ISSUE TITLE
DNS Privacy settings disappeared?

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#332]
Not sure if it's on purpose but I remember a UI related to DNS & Privacy, like disable logging on certain hosts or thing like this. Was this removed on purpose?

Cheers

**Comment by lts-rad** [comment]
<img width="469" alt="image" src="https://github.com/spr-networks/super/assets/37549748/b6286b36-39e9-4397-a3c9-6518cc12f313">
they are on the settings page under logs. perhaps too hidden

**Comment by 0vercl0k** [comment]
Oh awesome, thanks for letting me know! Seems fair to me for them to be here vs in their own UI.

Closing!

Cheers

**Comment by 0vercl0k** [comment]
Actually, although it is available in the web UI; has this been relocated somewhere else on the iOS app or is it not available there anymore?

Cheers

**Comment by lts-rad** [comment]
Ah yes, looks like it's gone fishing. Will fix! We are going to use a panel here for the new release, in dev branch

**Comment by 0vercl0k** [comment]
Actually there's also another case that's problematic: if you turned on privacy on a host before, it means there's no DNS history available for that device and it also means the 'settings' button doesn't even appear in the Web UI; so you can't change the configuration of that device anymore.

Cheers

**Comment by lts-rad** [comment]
Will fix this on mobile

**Comment by 0vercl0k** [comment]
Woot thanks for fixing this!

**Comment by lts-rad** [comment]
Thanks for reporting -- sorry for the awkwardness

**Comment by 0vercl0k** [comment]
A few follow-ups on this:
- In DNS Log, the 'Log settings' tab has the old controls to remove the entries; they don't support the left swipe / are a bit awkward to click on the ❌button
- There is no way to clear the history for a device as far as I can tell on the application but maybe I am missing something?

Cheers

**Comment by 0vercl0k** [comment]
bumping, cc @lts-rad to make sure it doesn't fall through the cracks 😅

**Comment by lts-rad** [comment]
for the clear history it looks like it went missing from the mobile view 
<img width="323" alt="image" src="https://github.com/user-attachments/assets/a1b313e8-e151-434b-a8d9-52f8c6a198eb">

**Comment by lts-rad** [comment]
this should be in the mobile view now. we have not released the new iOS app to testflight yet though /cc @lts-po

**Comment by 0vercl0k** [comment]
hell yeah, I can see this in the latest flight, awesome! Thank you both.
