### ISSUE TITLE
DNS Permit Override applies to all clients

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#338]
I have set-up a DNS permit override for a specific client, but it seems like this entry is also permitted for at least another client - let me know if you want me to turn on specific logging or whatnot.

Cheers

**Comment by 0vercl0k** [comment]
Okay I think this is my fault, my bad 😅

**Comment by lts-rad** [comment]
for debugging this, do you have any suggestions on UI to make it easier ?
