### ISSUE TITLE
Auto expiring devices don't get cleaned up in DNS Host Privacy list

### ISSUE THREAD

**Issue by 0vercl0k** [spr-networks/super#342]
It seems that if an expiring devices is added to any of the DNS log settings they actually don't get removed when the device expired. The device disappeared but its IP still is in the Host Privacy IP list.

Cheers

**Comment by lts-rad** [comment]
coredns-jsonlog has a branch to test now for handling the delete event from api, new in v0.3.14

**Comment by lts-rad** [comment]
v0.3.14 is now released
