### ISSUE TITLE
Cannot select Speed Test from menu on mobile

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#42]
See attached from iOS 15 on an iPhone 12 mini. I cannot scroll the menu to get to the Speed Test option. (Clip is slightly trimmed in the middle to fit on GitHub.)

Also it seems possible to scroll the page under the menu somehow (see end of clip).

https://user-images.githubusercontent.com/108767/181653771-ff7dc573-5b1e-4d1d-ac48-a118ee639500.mov

**Comment by lts-rad** [comment]
This should be resolved now
