### ISSUE TITLE
Dragging to switch tabs under Wifi sometimes gets glitchy 

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#43]
Usually dragging on empty space will switch tabs smoothly. Occasionally though it gets into a glitchy state where it will snap suddenly if the mouse is dragged at all. In the video, it starts out working OK, but after I interact with the Frequency Band popup, the smoothness is replaced but sudden tab switches.

I've previously seen it where it interpreted interacting with the popups or buttons as drags instead of clicks, which is why I was clicking randomly.

I think the dragging behavior should be disabled for mouse events since it is more of a touch-based gesture.

https://user-images.githubusercontent.com/108767/181654276-53c0c6c5-493b-42c6-90be-26f76d0289d7.mov

**Comment by lts-rad** [comment]
Gluestack should have fixed this
