### ISSUE TITLE
Add clients to DNS log privacy by name not IP

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#53]
I'm asked for an IP to add to the "Host Privacy IP List" but I'd like to be able to select a Wi-Fi client by name. Or just add a tag or something in the clients list, rather than use this interface separately?

**Comment by lts-rad** [comment]
@lts-po we have UI to do this, we should update that

**Comment by lts-rad** [comment]
Dev branch has a fix for this now.
https://github.com/spr-networks/super/commit/97c033bd9b7dd9f8191762f0698d9294e107c8bd
