### ISSUE TITLE
UI bug: add device plus covers ... for modifying device groups/users

### ISSUE THREAD

**Issue by lts-rad** [spr-networks/super#59]
@lts-po

**Comment by lts-rad** [comment]
![image](https://user-images.githubusercontent.com/37549748/188500935-ae555a26-d6b5-489e-aa04-16c3f16efb45.png)

**Comment by lts-po** [comment]
fixed in dev https://github.com/spr-networks/super/commit/f08de8e884156620151d02276dddc487fab1205e
