### ISSUE TITLE
Glitchy SSID entry for first-time setup on Safari

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#64]
The cursor position jumps while entering a value into the "Wifi Name" field on the web interface when doing first-time setup on Safari. I could not reproduce on Chrome. Also Safari tries to autocomplete a name from my contacts which might be related.

**Comment by lts-rad** [comment]
@lts-po was this related to react 18?

**Comment by lts-po** [comment]
the contact autocomplete is fixed in current version - tested with Safari, glitch is resolved.

@rgov
