### ISSUE TITLE
Device list ••• menu closes abruptly while trying to use it

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#70]
This is on Safari 16 on macOS 12.6. The device list extends below the bounds of the browser window. When I use the ••• menu and try to delete an entry, the menu abruptly closes as I get close to the "Delete" menu item. I have to extend the window size to get it to work.

![2022-09-19 13 10 46](https://user-images.githubusercontent.com/108767/191075127-96b4978e-4d88-4a57-9f86-9cd81f04d927.gif)

**Comment by rgov** [comment]
Reproduces in Chrome as well.

**Comment by lts-rad** [comment]
This was previously addressed by rolling back a react component
