### ISSUE TITLE
Device connection shows as successful in error

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#71]
I had a device routinely trying and failing to authenticate to the network. I waited for the auth failure popup and copied the MAC address, then used the Add Device flow to add a new entry with the same MAC address and (it turned out) the wrong password.

On the QR code screen, the connection status immediately changed to "Success" even though there was no successful attempt. And when the device did attempt to connect a moment later, I got the PSK failure alert.

**Comment by lts-rad** [comment]
Was it actually successful in the end? Hostap has to trigger a succesful association event for that popup to appear

**Comment by rgov** [comment]
It successfully authed later but not instantaneously as shown. It took maybe 30 seconds for the device to retry.

**Comment by lts-rad** [comment]
Could be a UI state glitch in that case, can try to reproduce later.

**Comment by rgov** [comment]
Updated answer above
