### ISSUE TITLE
ER: Copy password from another device

### ISSUE THREAD

**Issue by rgov** [spr-networks/super#72]
To ease setup of devices that share an iCloud Keychain or similar syncing mechanism, I'd like to be able to clone the password from an existing device, without having to go looking for what the donor device's password is.

**Comment by lts-rad** [comment]
<img width="205" alt="Screen Shot 2023-04-24 at 5 45 45 PM" src="https://user-images.githubusercontent.com/37549748/234147968-c16ee091-92d8-4ed5-9f74-e63f247f326b.png">

marking as closed, this was added but i don't remember in which release.
